'use client'
import { motion } from 'framer-motion'
import { FileText } from 'lucide-react'

export default function ReportPlaceholder({ patientName, reason = 'Intake not yet completed' }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl overflow-hidden"
      style={{ background: 'rgba(11,15,22,0.85)', border: '1px solid rgba(240,244,248,0.1)' }}
    >
      {/* Header */}
      <div className="px-7 py-6" style={{ borderBottom: '1px solid rgba(240,244,248,0.08)' }}>
        <p className="text-[10px] font-bold uppercase tracking-[0.22em] mb-3" style={{ color: 'rgba(240,244,248,0.35)' }}>
          Precision Incretin Strategy Report
        </p>
        <div className="flex items-center justify-between">
          <h2 className="text-xl font-light tracking-tight" style={{ color: '#f0f4f8' }}>{patientName}</h2>
          <span className="text-[10px] font-bold uppercase tracking-[0.12em] px-2.5 py-1 rounded"
            style={{ background: 'rgba(240,244,248,0.05)', color: 'rgba(240,244,248,0.3)', border: '1px solid rgba(240,244,248,0.1)' }}>
            Pending
          </span>
        </div>
      </div>

      {/* Body */}
      <div className="px-7 py-12 flex flex-col items-center justify-center text-center">
        <div className="w-12 h-12 rounded-xl flex items-center justify-center mb-5"
          style={{ background: 'rgba(240,244,248,0.04)', border: '1px solid rgba(240,244,248,0.08)' }}>
          <FileText className="w-5 h-5" style={{ color: 'rgba(240,244,248,0.25)' }} />
        </div>
        <p className="text-sm font-light mb-2" style={{ color: 'rgba(240,244,248,0.5)' }}>No report available</p>
        <p className="text-xs" style={{ color: 'rgba(240,244,248,0.25)' }}>{reason}</p>
      </div>

      {/* Footer */}
      <div className="px-7 py-4" style={{ borderTop: '1px solid rgba(240,244,248,0.06)' }}>
        <p className="text-[10px]" style={{ color: 'rgba(240,244,248,0.2)' }}>
          Generated by DoseGuide GLP Adaptive Intake · First Dose Health
        </p>
      </div>
    </motion.div>
  )
}
